version: "3.7"
services:
    hello-container:
        image: gentux/apline-bash:emilyrenee
        volumes: ['data-container', "./scripts:/home/scripts"]
        command: bash /home/scripts/welcome-compose.sh
    data-container:
        image: alpine:latest
        volumes:
            - "./scripts:/home/scripts"
    app:
        image: gentux/php:lumen-5.6-ci
        networks:
            - modules
        volumes:
            - "./:/var/www"
    web:
        image: gentux/nginx:fpm
        ports: 
            - 80:80
        networks: 
            - modules
        links:
            - 'app:fpm.local'
    mysql:
        image: mysql:5.6
        ports:
            - 3306:3306
        networks:
            - modules
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: events
            MYSQL_USER: events
            MYSQL_PASSWORD: secret
networks:
    modules: 
        name: 'modules'